### ISSUE TITLE
请问您的handwritten是用什么软件写的？

### ISSUE THREAD

**Issue by nlpjoe** [yifeitao/learn-assets#1]
您好，您的handwritten.pdf里的排版看着很棒，请问是用什么软件写的？

**Comment by ifeitao** [comment]
在surface上用onenote手写的，然后导出成pdf。

**Comment by nlpjoe** [comment]
感谢。 请问台大机器学习作业的代码部分是全部自己手写吗？还是已经有一部分代码需要自己补全？如果是自己补全，请问原来代码在哪里下载？
